### ISSUE TITLE
拖拽问题。 Dragging Problem.

### ISSUE THREAD

**Issue by hehe-minecraft** [dddddgz/star-motion-simulate#1]
# Bug Feedback

## Version

1.1 Release

## Word Description

当我先将屏幕缩放，再使用鼠标拖拽的时候，拖拽的距离有点问题：似乎拖拽的距离还是按照原来放大倍数（1倍）来算的。
When I drag the screen after scaling, the distance isn't correct enough: It seemed to be like dragging in the original scale.

## Reproduction Steps

1. 在游戏区域滚动鼠标滚轮（向一个方向越久越好）。Scroll the mouse wheel in the game area (on one direction; longer is better).
2. 拖拽背景。Drag the background.

## Screenshots and Video

[Pygame Star Motion Simulate.zip](https://github.com/dddddgz/star-motion-simulate/files/12223547/Pygame.Star.Motion.Simulate.zip)

**Comment by dddddgz** [comment]
已修复，经过测试发现bug原因是偏移量用的是 `event.rel`，偏移量没有修复
